######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 21 15:52:00 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lcgxmlparser.h
SOURCES += lcgxmlparser.cpp main.cpp
